name: Integration Tests and deployments

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        run: forge fmt --check

      - name: Check gas snapshots
        run: forge snapshot --check --fork-url ${{ secrets.FORK_URL }}

      - name: Install dependencies
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes

      - name: Run tests
        run: forge test --fork-url ${{ secrets.FORK_URL }}
        env:
          FOUNDRY_PROFILE: integration

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Deploy to Goerli testnet
        run: forge script src/DMSD.s.sol:DMSDScript --rpc-url ${{ secrets.FORK_URL }} --private-key ${{ secrets.GOERLI_PRIVATE_KEY }} --etherscan-api-key ${{ secrets.ETHERSCAN_API_KEY }} --broadcast -vvvv
